#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
jsFiles=`git diff --cached HEAD --name-only|grep "^tarjonta-app-angular/.*\.js$"`
if [ "$jsFiles" ]; then
    jshintOutput=`jshint --config tarjonta-app-angular/.jshintrc $jsFiles`
    # Jshint ei jostain syystä käytä oikeaa exit arvoa, joten pitää itse hoitaa
    if [ "$jshintOutput" ]; then
        echo "KORJAA JAVASCRIPTIN VIRHEET!\n"
        echo "$jshintOutput"
        exit 1
    else
        jscs --config tarjonta-app-angular/.jscsrc $jsFiles
    fi
fi
