sudo: required

language: java

jdk:
- openjdk8

services:
- docker

cache:
  directories:
  - $HOME/.m2

env:
  global:
    # ARTIFACTORY_USERNAME
    - secure: "iRcpqzja5iWCvOInCBBYPeYbOecTad/g59avGlE3HKVj2ntdmCNcWqAvsn2cIxJlXqtmmk7cAj/pev9eaJyW8qYr0PvKnzQnu3/HVOVLfhhtWlBQQ01oWiNriu8w7P3mARWFXFOEpeN3Ycb11rT2HS2iafteKK+9EYaRRySzDJocxS70B2DbCwnY15L/bEOuvSQuCh3fSCavBd/XJBXfs0MZ0ynsMS+aTraK8LX1IpriRfQHdXEBy8Eq504pgbBvScLfvVBsx285bWbOXvaBXDXCD/zEjBFwBz6Wwkt/KwjJJidJTv1WyXvEK6QaYoiiB8P/+92mtGkrrkl/hJlXwq3Xo6V7mh6K3TOWLuvZHZUnTFRGDXNyzZwmT9aJylkfhIIOF73cE9oQJkoPKtTHRAMUj7WogYznVFM2VSKY4k61TvitEdSc+qXPGUbJtspX0nVkCLejL18av0sj9XOUsMF4owkOG8nhwnMRd4vbKAaWYTs9LcOR4Le+E9FC4xMKdOmEADDs5cVWM73us+S3MVy4vo385oHezRpqJfBtXnrQwsbs9gqkGkwvMwQC+iWcW56AkVRMtxac9fOw19wnUhWk7rzlHaUuH9H+9DIljkUnoVXqfoA8GC36/NMtkH1oQciejN+vYktoLydzQ4vpYCGIZYxCt7BOGE5OUlFZKl0="
    # ARTIFACTORY_PASSWORD
    - secure: "Y75nfIrSUSS0/86ZzCuhR9BsDICEuN29YI9S4BPRbBaqzEdEqGsWT7gFzpOmzmlW9P/a9UN0y78UcEaafQsSHC/0ILn+o1RtcdefxjR86O9FGZ7AQTqerNQPPKcXYuOVQEffA8Yr1KjRRc4+oc9fwQqnoZZw1bTkHT2GPxfg5sH39b4KaAxvaGZFvpv0Re9R4JgojXJ98aD7CzXjE0F5YBQEnODmCJuNX6jxJo5CCPqk45qTXnw1+qqbv0ycQncm8PXB1HY2rUX7yY2Z1KOd7Jo27aBt+fBnok5z9x9f/S9i1uoGkuT+pQ3mpm2P+9trWmB4qc9qU7xkJpjTNQG7R5YL8iOpL7cvAGy70PTAZTgA0NKWaCo24P0qyeUlIgmCL2SrZS/hRojxPrTI3mT8DQPulpbErDzTZbjFQjBjCIsd9ndyij/ZEOUiN7RydsRokZzoAFJultyijW2RsKanic6WE0M8l9dVF4cGPlvvmpbxiWkq2mDKFBcRixboMJqKvn4UphWAIrHnN50/HGQcSRZoYGcPK67jidFN8C0TM6vavlpjWV29Z/y8OkLlMPLv0Z7h/2aCmYUJ+bpy8M+JxdtysGnv9kTkqMEGdiMjm4/iMbVfGsD5RThEST9GE2ZSP9gD+LBEbPEsrzicXMTvPPQYwPfNYCy/rt6QyRkNEs4="
    # AWS_ACCESS_KEY_ID
    - secure: "PveSaf5EXgOk2LFpZ1bolHwUPPfm9Ys8bE8Fxr2hxoyieMkCtpyZTMr087NrSYnKeVzWYpuuFiJrJ+mags0fomnSUhg6l/+76y6y8r7XuzgzxzC93TFILDQClAwhJ76wZ54ldOBWuwHoOpAiapfpw2YtokYW9Oysncdxw59YpFZfMiUJjpUGXRJxMvNaLyZK9t71+Vuobn28tOYFSY8mYBVsfAWENOZI8hasjQzytoyRLC5XpZNgY9xLDZbAzBRReYjNgjix45fh4j+XKlVUtSjUrzt73co+XCP+Zi5r1VwB2chxWQ748NPyt5D/z0HNor3WCRSf/84duvJYi2Nbpr4gHpYXuIz/qhEChuW7Jt8Kgy9CX+MCjdETQDgs27fXSAkTn51j8WL4mcCsTvOBDXgkNiOSY35cABfTDYAOXep4pxkk7+5WckUOHY0qbatKmFkuAzvL/NtqMphMy480FaPHJJvibzfzLE9z+y1Oq5ORA/a43XoQguCDQa3/lNbKIPEHKNec7KPS7t+y0MmLXY/KfRGohxbjBi70dH689Vv/0Rvf3aFsHB9p/5AHfG2ZzvJVDj/r37Hofg7zoF64aIH4/jZe4YXMx4CbIfU4LTZMmUwEWcCQRn/i0LJ0ZSoRn8DTNGpIXOs1navk0kW+pnBjT3sR8o0G/XHrM7+Am8I="
    # AWS_SECRET_ACCESS_KEY
    - secure: "DpghpxAmNv35iUV/6x53WcYNJAdKyfyL6Mo1YjjAVUW/ha1/Zt14aN82BfTQEXluMcmihRpjb2l+A8xfSNw5oIxBTnqg7VglIjMFHrRlbrIuCGpWPCkzRLTTys437lqqTaiUds+PICd8HML1D78AEXhoY+jHl0hYwebbFBe4Wbmgkg5UFS8GcKg2ZnyIHkipAOhKkgGHEFwHx801D2oOi1l4hVVcEZTHP6l4TGEz5ijNeFAiXsBjBW3DQ4nyq5d2B+/FPDL4tPzeqix2LPgfFx3jyeGEdoa1qSKVemQnMsq1PiKo/H4vZxZ7KS3Fk2HA7eDsgnwUIyF1wLn39eGCXCNM1sWpMXbX/d4XqXA/fjBpzp0qea+KxdRQRHIYjcFB55AEFHloKeohGmgF0WYfFBJcbk3osvk9KfBSFEP7bCVyaJUN2GO2IwSRr2gt55pVzipx0E5BZmdbZR0RTfHfrUUrN7fGX5XiO7RVusuKRIZb+318LYJYgWIZaf7icZPYDhCigYn1Llm+lzUU5b2fpjWHtJ9WfLSiJ0kzMHbqlGLD0vfpuCbma6XRiipT+zXqr7bRxldICh3TRBgOHd9iozx+5Rn3BCu4IAeK4AAiMhRMYuvqu3+/Hsb2Q7AAr2zzxKueWHO9BiFKN2TIZa5IAKrL4g97hjTuDTtfp0cL9Vs="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- export ARTIFACT_NAME="tarjonta"
- export TZ=Europe/Helsinki
- date

script:
- mvn clean package -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

- mv tarjonta-service/target/tarjonta-service.war $DOCKER_BUILD_DIR/artifact/tarjonta-service.war
- mv tarjonta-app/target/tarjonta-app-*.war $DOCKER_BUILD_DIR/artifact/tarjonta-app.war
- cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

- export BASE_IMAGE="baseimage-war-openjdk8:master"
- ./ci-tools/common/pull-image.sh
- ./ci-tools/build/build-war.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script: mvn deploy -pl tarjonta-api,tarjonta-shared -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
    on:
      all_branches: true
