<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="koulutusAdminService"
                  targetNamespace="http://service.tarjonta.sade.vm.fi/"
                  xmlns:ns1="http://service.tarjonta.sade.vm.fi/types"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://service.tarjonta.sade.vm.fi/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema targetNamespace="http://service.tarjonta.sade.vm.fi/">
            <xsd:import namespace="http://service.tarjonta.sade.vm.fi/types" schemaLocation="OPHKoulutusAdminService.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="createKoulutus">
        <wsdl:part element="ns1:createKoulutus" name="parameters">
        </wsdl:part>
    </wsdl:message>
    
    <wsdl:message name="createKoulutusResponse">
        <wsdl:part element="ns1:createKoulutusResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    
    <wsdl:portType name="KoulutusAdminService">
        <wsdl:documentation>
            Admin service for managing "koulutus tarjonta".
        </wsdl:documentation>
        <wsdl:operation name="createKoulutus">
            <wsdl:documentation>
                Create Koulutus from passed data. This actual effect of this method is dependant on 
                user authorization level. 
            </wsdl:documentation>
            <wsdl:input message="tns:createKoulutus" name="createKoulutus">
            </wsdl:input>
            <wsdl:output message="tns:createKoulutusResponse" name="createKoulutusResponse">
            </wsdl:output>
        </wsdl:operation>        
    </wsdl:portType>

    <wsdl:binding name="KoulutusAdminServiceSoapBinding" type="tns:KoulutusAdminService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="createKoulutus">
            <soap:operation soapAction="" style="document" />
            <wsdl:input name="createKoulutus">
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output name="createKoulutusResponse">
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>        
    </wsdl:binding>

    <wsdl:service name="KoulutusAdminService">
        <wsdl:port name="KoulutusAdminServicePort" binding="tns:KoulutusAdminServiceSoapBinding">
            <soap:address location="http://localhost:8181/cxf/koulutusAdminService" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>