package fi.vm.sade.tarjonta.shared.types;

public enum KomotoTeksti {
  LISATIEDOT,
  EDELTAVAT_OPINNOT,
  OPETUKSEN_AIKA_JA_PAIKKA,
  MAKSULLISUUS,
  ARVIOINTIKRITEERIT,
  LOPPUKOEVAATIMUKSET,
  PAINOTUS,
  KOULUTUSOHJELMAN_VALINTA,
  KUVAILEVAT_TIEDOT,
  SISALTO,
  SIJOITTUMINEN_TYOELAMAAN,
  KANSAINVALISTYMINEN,
  YHTEISTYO_MUIDEN_TOIMIJOIDEN_KANSSA,
  LISATIETOA_OPETUSKIELISTA,
  TUTKIMUKSEN_PAINOPISTEET,
  PAAAINEEN_VALINTA,
  OPPILAITOSKOHTAISET_OPPIAINEET_JA_KURSSIT,
  KOHDERYHMA, // aikuislukio + pervakot
  OPPIAINEET_JA_KURSSIT, // aikuislukio
  OSAAMISALAN_VALINTA, // amm nayttotutkintona
  NAYTTOTUTKINNON_SUORITTAMINEN, // amm nayttotutkintona
  OPISKELUN_HENKILOKOHTAISTAMINEN; // amm nayttotutkintona
}
